spring:
  profiles:
    active: dev
  application:
    name: treeple-api

---

spring:
  profiles: dev, test
server:
  port: 8000
client:
  web:
    ip: localhost
    port: 5000

---

spring:
  profiles: prod
server:
  port: ${PORT:8000}
client:
  web:
    ip: localhost
    port: 5000
